[workspace]

members = [
    "utils/flat",
    "utils/math",
    "utils/strings",
    "utils/debug",
    "day-01",
    "day-02",
    "day-03",
    "day-04",
    "day-05",
    "day-06",
]
resolver = "2"
